#
# Copyright (c) 2022 StarTree Inc. All rights reserved.
# Confidential and Proprietary Information of StarTree Inc.
#

FROM apachepinot/pinot:latest

WORKDIR /home/thirdeye

COPY resources resources

ENTRYPOINT ["sh", "resources/thirdeye-quickstart-pinot.sh"]
