# Label when configuration files in ThirdEye UI project root change
thirdeye-ui config:
    - "thirdeye-ui/*"
    - "thirdeye-ui/.*"
    - ".github/pr-labels.yaml"
    - ".github/workflows/pr-labels.workflow.yaml"
    - ".github/workflows/thirdeye-ui-merge.workflow.yaml"
    - ".github/workflows/thirdeye-ui-pr.workflow.yaml"
    - "thirdeye-ui/.vscode/**/*"

# Label when source files in ThirdEye UI project change
thirdeye-ui:
    - "thirdeye-ui/src/**/*"
