# Label when configuration files in ThirdEye UI project root change
thirdeye-ui config:
    - ".github/pr-labels.yaml"
    - ".github/workflows/thirdeye-ui-pr.workflow.yaml"
    - "thirdeye-ui/*"
    - "thirdeye-ui/.*"
    - "thirdeye-ui/.vscode/**/*"
    - "thirdeye-ui/docker/**/*"
    - "thirdeye-ui/scripts/**/*"

# Label when source files in ThirdEye UI project change
thirdeye-ui:
    - "thirdeye-ui/src/**/*"
