### Threshold Alert
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "THRESHOLD",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.max": "${max}",
            "component.min": "${min}",
            "component.offset": "mo1m",
            "component.pattern": "down",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "current",
              "sourcePlanNode": "missingDataManager",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "missingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts) GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "max": "850000",
      "min": "300000"
    }
  },
  "start": "1613376000000",
  "end": "1627714800000"
}


### Holt Winters
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "HOLT_WINTERS",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.pattern": "${pattern}",
            "component.sensitivity": "${sensitivity}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "current",
              "sourcePlanNode": "missingDataManager",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "missingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts, '${lookback}') AND ts < ${endTime} GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "lookback": "P7D",
      "pattern": "DOWN",
      "sensitivity": "1"
    }
  },
  "start": "1613376000000",
  "end": "1627714800000"
}

### Absolute Change
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "dryRun": false,
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "ABSOLUTE_CHANGE",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.absoluteChange": "${absoluteChange}",
            "component.offset": "${offset}",
            "component.pattern": "${pattern}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "baseline",
              "sourcePlanNode": "baselineMissingDataManager",
              "sourceProperty": "baselineOutput"
            },
            {
              "targetProperty": "current",
              "sourcePlanNode": "currentMissingDataManager",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "baselineMissingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "baselineDataFetcher",
              "sourceProperty": "baselineOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "baselineDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts, '${lookback}', '${lookback}') GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "currentMissingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts) GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "absoluteChange": "100000",
      "offset": "wo1w",
      "lookback": "P1W",
      "pattern": "down"
    }
  },
  "start": "1612170000000",
  "end": "1626771600000"
}

### Mean Variance
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "MEAN_VARIANCE",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.lookback": "${lookbackDetector}",
            "component.sensitivity": "${sensitivity}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "current",
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "currentMissingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts, '${lookback}') GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "lookback": "P12D",
      "lookbackDetector": "12",
      "sensitivity": "1"
    }
  },
  "start": "1613376000000",
  "end": "1627714800000"
}

### Percentage Change
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "dryRun": false,
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "PERCENTAGE_CHANGE",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.percentageChange": "${percentageChange}",
            "component.offset": "${offset}",
            "component.pattern": "${pattern}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "baseline",
              "sourcePlanNode": "baselineMissingDataManager",
              "sourceProperty": "baselineOutput"
            },
            {
              "targetProperty": "current",
              "sourcePlanNode": "currentMissingDataManager",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "baselineMissingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "baselineDataFetcher",
              "sourceProperty": "baselineOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "baselineDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts, '${lookback}', '${lookback}') GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "currentMissingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts) GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "percentageChange": "0.1",
      "offset": "wo1w",
      "lookback": "P7D",
      "pattern": "down"
    }
  },
  "start": "1613376000000",
  "end": "1627714800000"
}
