POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "id": 25677
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}

###
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "name": "newAlertTemplate"
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}

###
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "name": "template-that-does-not-exist"
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}

### DRY RUN Feature
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "dryRun": true,
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "name": "newAlertTemplateWithProp"
    },
    "templateProperties": {
      "percentageChangeValue": 0.123
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}

###
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "name": "newAlertTemplateWithProp"
    },
    "templateProperties": {
      "percentageChangeValue": 0.1
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}


### Test alert for a single day with live template
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "v1Format": true,
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "component.detector.timestamp": "ts",
            "component.detector.metric": "met",
            "component.detector.dimensions": [],
            "component.detector.timezone": "US/Pacific",
            "component.detector.monitoringGranularity": "1_DAYS",
            "component.detector.type": "THRESHOLD",
            "component.detector.max": "850000",
            "component.detector.min": "300000",
            "component.detector.offset": "mo1m",
            "component.detector.pattern": "down"
          },
          "inputs": [
            {
              "targetProperty": "current",
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.pinot.className": "org.apache.pinot.thirdeye.detection.v2.components.datafetcher.GenericDataFetcher",
            "component.pinot.dataSource": "pinotQuickStartLocal",
            "component.pinot.query": "SELECT DATETIMECONVERT(\"date\", '1:DAYS:SIMPLE_DATE_FORMAT:yyyyMMdd', '1:MILLISECONDS:EPOCH', '1:DAYS') as ts, sum(views) as met FROM pageviews WHERE ts >= ${startTime} AND ts < ${endTime} GROUP BY ts ORDER BY ts LIMIT 1000",
            "component.pinot.tableName": "pageviews"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}
