GET http://localhost:7004/api/rca/metrics/heatmap?id=247717&baselineOffset=P1W
Accept: application/json

###

GET http://localhost:8080/api/rca/metrics/heatmap?id=247717&baselineOffset=P1W&filters=device=desktop
Accept: application/json
