{{ if .Values.scheduler.enabled }}
#
# Copyright 2022 StarTree Inc
#
# Licensed under the StarTree Community License (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.startree.ai/legal/startree-community-license
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT * WARRANTIES OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and limitations under
# the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirdeye.scheduler.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.scheduler.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "thirdeye.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.scheduler.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thirdeye.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.scheduler.name }}
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/scrape: {{ .Values.prometheus.enabled | quote }}
        {{- toYaml .Values.scheduler.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName | quote}}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.scheduler.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.scheduler.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.scheduler.tolerations | nindent 8 }}
      initContainers:
      - name: init-keystore
        image: eclipse-temurin:17-jdk
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        - >
          {{- if .Values.tls.scheduler.enabled }}
          echo "importing internal tls key" &&
          openssl pkcs12 -export -name internalTls -in /opt/thirdeye/server/tls-internal/tls.crt -inkey /opt/thirdeye/server/tls-internal/tls.key -out /opt/thirdeye/server/keystore-internal.p12 -password pass:changeit &&
          keytool -noprompt  -importkeystore -alias internalTls -srckeystore /opt/thirdeye/server/keystore-internal.p12 -srcstoretype PKCS12 -srcstorepass changeit -deststorepass changeit -destkeystore /opt/thirdeye/server/keystore/keystore &&
          {{- end }}
          echo "importing ca cert" &&
          if [ -e /opt/thirdeye/server/tls-internal/ca.crt ];
          then 
              keytool -noprompt  -import -alias startreePlatformCa -srcstorepass changeit -deststorepass changeit -keystore /opt/java/openjdk/lib/security/cacerts -file /opt/thirdeye/server/tls-internal/ca.crt
          fi &&
          cp /opt/java/openjdk/lib/security/cacerts /opt/thirdeye/server/truststore/truststore
        volumeMounts:
        - name: tls-internal
          mountPath: /opt/thirdeye/server/tls-internal
          readOnly: true
        {{- if .Values.tls.scheduler.enabled }}
        - name: keystore
          mountPath: /opt/thirdeye/server/keystore
        {{- end }}
        - name: truststore
          mountPath: /opt/thirdeye/server/truststore
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "server"
        env:
          {{- range $name, $secret := .Values.secrets }}
          {{- if and $secret.env $secret.value }}
          - name: {{ $secret.env }}
            valueFrom:
              secretKeyRef:
                name: thirdeye-secrets
                key: {{ $name }}
          {{- end }}
          {{- end }}
          - name: JAVA_OPTS
            value: >
              {{- if .Values.tls.scheduler.enabled }}
              -Djavax.net.ssl.keyStore=/opt/thirdeye/server/keystore/keystore
              -Djavax.net.ssl.keyStorePassword=changeit
              {{- end }}
              -Djavax.net.ssl.trustStore=/opt/thirdeye/server/truststore/truststore
              -Djavax.net.ssl.trustStorePassword=changeit {{.Values.scheduler.javaOpts}}
        ports:
          - containerPort: {{ .Values.scheduler.port }}
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          {{- if .Values.tls.scheduler.enabled }}
          - containerPort: {{ .Values.tls.port }}
            protocol: TCP
          {{- end }}
        volumeMounts:
          - name: thirdeye-config
            mountPath: "/home/thirdeye/thirdeye/config/server.yaml"
            subPath: "server.yaml"
            readOnly: true
          {{- if .Values.secrets.holidayLoaderKey }}
          - name: holiday-loader-key
            mountPath: "/home/thirdeye/thirdeye/config/holiday-loader-key.json"
            subPath: holidayLoaderKey
            readOnly: true
          {{- end }}
          {{- if .Values.tls.scheduler.enabled }}
          - name: keystore
            mountPath: /opt/thirdeye/server/keystore
            readOnly: true
          {{- end }}
          - name: truststore
            mountPath: /opt/thirdeye/server/truststore
            readOnly: true
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: thirdeye-config
          configMap:
            name: thirdeye-scheduler
        - name: tls-internal
          secret:
            secretName: {{ .Values.tls.scheduler.secretName | default (printf "%s-internal-tls" (include "thirdeye.scheduler.fullname" .)) }}
            optional: true
        - name: truststore
          emptyDir: {}
        {{- if .Values.tls.scheduler.enabled }}
        - name: keystore
          emptyDir: {}
        {{- end }}
        {{- if .Values.secrets.holidayLoaderKey }}
        - name: holiday-loader-key
          secret:
            secretName: thirdeye-secrets
        {{- end }}
  strategy:
    {{- toYaml .Values.scheduler.strategy | nindent 4 }}
{{ end }}
