
{{ if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirdeye.scheduler.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.scheduler.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "thirdeye.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.scheduler.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thirdeye.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.scheduler.name }}
      annotations:
        prometheus.io/port: {{ .Values.scheduler.port | quote }}
        prometheus.io/path: "/admin/prometheus"
        {{- toYaml .Values.scheduler.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName | quote}}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.scheduler.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.scheduler.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.scheduler.tolerations | nindent 8 }}
      {{- if .Values.tls.enabled }}
      initContainers:
      - name: init-keystore
        image: eclipse-temurin:17-jdk
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        - >
          echo "importing internal tls key" &&
          openssl pkcs12 -export -name internalTls -in /opt/thirdeye/server/tls-internal/tls.crt -inkey /opt/thirdeye/server/tls-internal/tls.key -out /opt/startree/platform/keystore-internal.p12 -password pass:changeit &&
          keytool -noprompt  -importkeystore -alias internalTls -srckeystore /opt/startree/platform/keystore-internal.p12 -srcstoretype PKCS12 -srcstorepass changeit -deststorepass changeit -destkeystore /opt/startree/platform/keystore/keystore &&
          echo "importing ca cert" &&
          keytool -noprompt  -import -alias startreePlatformCa -srcstorepass changeit -deststorepass changeit -keystore /opt/java/openjdk/lib/security/cacerts -file /opt/thirdeye/server/tls-internal/ca.crt &&
          cp /opt/java/openjdk/lib/security/cacerts /opt/thirdeye/server/keystore/truststore
        volumeMounts:
        - name: tls-internal
          mountPath: /opt/thirdeye/server/tls-internal
          readOnly: true
        - name: keystore
          mountPath: /opt/thirdeye/server/keystore
      {{- end }}
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "server"
        {{- if .Values.tls.enabled }}
        env:
          - name: JAVA_OPTS
            value: >
              -Djavax.net.ssl.keyStore/opt/thirdeye/server/keystore/keystore
              -Djavax.net.ssl.keyStorePassword=changeit
              -Djavax.net.ssl.trustStore=/opt/thirdeye/server/keystore/truststore
              -Djavax.net.ssl.trustStorePassword=changeit
        {{- end }}
        ports:
          - containerPort: {{ .Values.scheduler.port }}
            protocol: TCP
        volumeMounts:
          - name: thirdeye-config
            mountPath: "/home/thirdeye/thirdeye/config/server.yaml"
            subPath: "server.yaml"
            readOnly: true
          {{- if .Values.config.holidayLoaderKey }}
          - name: thirdeye-config
            mountPath: "/home/thirdeye/thirdeye/config/holiday-loader-key.json"
            subPath: "holiday-loader-key.json"
            readOnly: true
          {{- end }}
          {{- if .Values.tls.enabled }}
          - name: keystore
            mountPath: /opt/thirdeye/server/keystore
            readOnly: true
          {{- end }}
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: thirdeye-config
          configMap:
            name: thirdeye-scheduler
        {{- if .Values.tls.enabled }}
        - name: tls-internal
          secret:
            secretName: {{ include "thirdeye.scheduler.fullname" . }}-internal-tls
        - name: keystore
          emptyDir: {}
        {{- end }}
{{ end }}
