{{- if and .Values.traefik.enabled .Values.scheduler.enabled -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ printf "%s-%s" (include "thirdeye.traefik.fullname" . ) "thirdeye" | trunc -63 }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Release.Namespace }}.{{ required "domain is required." .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ include "thirdeye.scheduler.headless" . }}
          servicePort: {{ .Values.scheduler.port }}
{{- end }}
