export interface StatusList {
    list: Status[];
}

export interface Status {
    code: ThirdEyeStatus;
    message: string;
}

export enum ThirdEyeStatus {
    ERR_DATASET_NOT_FOUND = "ERR_DATASET_NOT_FOUND",
    ERR_MULTIPLE_DATASETS_FOUND = "ERR_MULTIPLE_DATASETS_FOUND",
    ERR_DATA_UNAVAILABLE = "ERR_DATA_UNAVAILABLE",
    ERR_DUPLICATE_NAME = "ERR_DUPLICATE_NAME",
    ERR_MISSING_ID = "ERR_MISSING_ID",
    ERR_UNEXPECTED_QUERY_PARAM = "ERR_UNEXPECTED_QUERY_PARAM",
    ERR_ID_UNEXPECTED_AT_CREATION = "ERR_ID_UNEXPECTED_AT_CREATION",
    ERR_INVALID_QUERY_PARAM_OPERATOR = "ERR_INVALID_QUERY_PARAM_OPERATOR",
    ERR_OBJECT_UNEXPECTED = "ERR_OBJECT_UNEXPECTED",
    ERR_OBJECT_DOES_NOT_EXIST = "ERR_OBJECT_DOES_NOT_EXIST",
    ERR_OPERATION_UNSUPPORTED = "ERR_OPERATION_UNSUPPORTED",
    ERR_TIMEOUT = "ERR_TIMEOUT",
    ERR_UNKNOWN = "ERR_UNKNOWN",
}
