---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: repo.startreedata.io/external-docker-registry/ci-java-11
    tag: latest

caches:
  - path: src/m2

inputs:
  - name: src

params:
  MVN_REPOSITORY_USERNAME: ((artifactory-username))
  MVN_REPOSITORY_PASSWORD: ((artifactory-password))
  GITHUB_PRIVATE_KEY: ((ssh-private-key))

run:
  path: src/.concourse/tasks/release-thirdeye/release-thirdeye.sh
