POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "sample-event-trigger",
    "description": "Use dataFetcher to query data to trigger console output",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "EventTrigger",
          "params": {
            "component.detector.type": "CONSOLE_OUTPUT"
          },
          "inputs": [
            {
              "targetProperty": "input",
              "sourcePlanNode": "dataFetcher",
              "sourceProperty": "output"
            }
          ],
          "outputs": [
          ]
        },
        {
          "name": "dataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.pinot.className": "org.apache.pinot.thirdeye.detection.v2.components.datafetcher.GenericDataFetcher",
            "component.pinot.dataSource": "pinotQuickStartLocal",
            "component.pinot.query": "SELECT \"date\" as ts, sum(views) as met FROM pageviews WHERE \"date\" >= 20200209 AND \"date\" <= 20200730 GROUP BY \"date\" ORDER BY \"date\" LIMIT 1000",
            "component.pinot.tableName": "pageviews"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "output"
            }]
        }
      ]
    }
  },
  "start": "1577865600000",
  "end": "1590994800000"
}
