### HoltWinters alert
## index filler without config - uses metadata passed by macros
## same result than with the manual config
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json


{
  "start": "{{start}}",
  "end": "{{end}}",
  "alert": {"name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "HOLT_WINTERS",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.pattern": "${pattern}",
            "component.sensitivity": "${sensitivity}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "current",
              "sourcePlanNode": "missingDataManager",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "missingDataManager",
          "type": "TimeIndexFiller",
          "inputs": [
            {
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": [
            {
              "outputName": "currentOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT __timeGroup(\"${timeColumn}\", '${timeColumnFormat}', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE __timeFilter(ts, '${lookback}') GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews_with_missing_data",
      "metric": "sum(views)",
      "monitoringGranularity": "P1D",
      "timeColumn": "date",
      "timeColumnFormat": "yyyyMMdd",
      "lookback": "P5D",
      "pattern": "DOWN",
      "sensitivity": "1"
    }
  }
}