### Threshold Alert
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "start": "1612483200000",
  "end": "1614470400000",
  "alert": {"name": "sample-alert",
    "description": "Sample description payload for testing",
    "cron": "0 0/1 * 1/1 * ? *",
    "template": {
      "nodes": [
        {
          "name": "root",
          "type": "AnomalyDetector",
          "params": {
            "type": "ABSOLUTE_CHANGE",
            "component.timezone": "US/Pacific",
            "component.monitoringGranularity": "1_DAYS",
            "component.timestamp": "ts",
            "component.metric": "met",
            "component.dimensions": [],
            "component.absoluteChange": "${absoluteChange}",
            "component.offset": "${offset}",
            "component.pattern": "${pattern}",
            "anomaly.metric": "${metric}"
          },
          "inputs": [
            {
              "targetProperty": "baseline",
              "sourcePlanNode": "baselineMissingDataManager",
              "sourceProperty": "baselineOutput"
            },
            {
              "targetProperty": "current",
              "sourcePlanNode": "currentDataFetcher",
              "sourceProperty": "currentOutput"
            }
          ],
          "outputs": []
        },
        {
          "name": "baselineMissingDataManager",
          "type": "SqlExecution",
          "params": {
            "sql.queries": [
              "select i.ts, baseline.met from (select UNIX_TIMESTAMP(TRUNC(TIMESTAMP(c1/1000),'DD'))*1000-${offsetDays}*24*3600*1000 as ts from UNNEST(SEQUENCE_ARRAY(${startTime},${endTime},24*3600*1000))) as i left join baseline on i.ts = baseline.ts where i.ts>=(${startTime}-${offsetDays}*24*3600*1000) and i.ts<(${endTime}-${offsetDays}*24*3600*1000) order by ts"
            ]
          },
          "inputs": [
            {
              "targetProperty": "baseline",
              "sourcePlanNode": "baselineDataFetcher",
              "sourceProperty": "baselineOutput"
            }
          ],
          "outputs": [
            {
              "outputKey": "0",
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "baselineDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT DATETIMECONVERT(\"${timeColumn}\", '${timeColumnFormat}', '1:MILLISECONDS:EPOCH', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE ts >= ADD(${startTime}, MULT(-${offsetDays}, 24, 60, 60, 1000)) AND ts < ADD(${endTime}, MULT(-${offsetDays}, 24, 60, 60, 1000)) GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "baselineOutput"
            }
          ]
        },
        {
          "name": "currentDataFetcher",
          "type": "DataFetcher",
          "params": {
            "component.dataSource": "${dataSource}",
            "component.query": "SELECT DATETIMECONVERT(\"${timeColumn}\", '${timeColumnFormat}', '1:MILLISECONDS:EPOCH', '${monitoringGranularity}') as ts, ${metric} as met FROM ${dataset} WHERE ts >= ${startTime} AND ts < ${endTime} GROUP BY ts ORDER BY ts LIMIT 1000"
          },
          "inputs": [],
          "outputs": [
            {
              "outputKey": "pinot",
              "outputName": "currentOutput"
            }
          ]
        }
      ]
    },
    "templateProperties": {
      "dataSource": "pinotQuickStartLocal",
      "dataset": "pageviews",
      "metric": "sum(views)",
      "monitoringGranularity": "1:DAYS",
      "timeColumn": "date",
      "timeColumnFormat": "1:DAYS:SIMPLE_DATE_FORMAT:yyyyMMdd",
      "absoluteChange": "100000",
      "offset": "wo1w",
      "offsetDays": "7",
      "pattern": "down"
    }
  }
}