{{- if and .Values.traefik.enabled .Values.tls.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "thirdeye.ui.fullname" . }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: HostSNI(`{{ .Release.Name }}.{{ .Release.Namespace }}.{{ required "domain is required." .Values.domain }}`)
    services:
    - name: {{ include "thirdeye.ui.headless" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.ui.port }}
  tls:
    passthrough: true
{{- end }}
