---
env:
    browser: true
    es2020: true
    node: true
    jest: true

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:jest/recommended
    - plugin:jest/style
    - plugin:jest-formatting/recommended
    - plugin:cypress/recommended
    - plugin:@typescript-eslint/recommended
    - prettier
    - prettier/react
    - prettier/@typescript-eslint

parser: "@typescript-eslint/parser"

parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react
    - react-hooks
    - jest
    - jest-formatting
    - "@typescript-eslint"

rules:
    # ESLint rules

    # Require a whitespace at the beginning of a comment
    spaced-comment:
        - error
        - always

    # Maximum line length for comments except trailing comments
    max-len:
        - error
        - comments: 100
          code: 200 # Set to not conflict with Prettier
          ignoreTrailingComments: true

    # Require braces around blocks
    curly:
        - error
        - all

    # Require parentheses around arrow function arguments
    arrow-parens:
        - error
        - always

    # Require blank line before certain statements
    padding-line-between-statements:
        - error
        - blankLine: always
          prev: "*"
          next: function
        - blankLine: always
          prev: "*"
          next: class
        - blankLine: always
          prev: "*"
          next: export
        # Ignore consecutive export statements
        - blankLine: any
          prev: export
          next: export
        - blankLine: always
          prev: "*"
          next: return
        - blankLine: always
          prev: "*"
          next: break
        - blankLine: always
          prev: "*"
          next: continue
        - blankLine: always
          prev: "*"
          next: throw

    # eslint-plugin-react rules

    # Require props to be sorted
    react/jsx-sort-props:
        - error
        - callbacksLast: true
          shorthandFirst: true

    # Omit boolean prop value when set to true
    react/jsx-boolean-value:
        - error
        - never

    # Require self closing tags in JSX/HTML
    react/self-closing-comp:
        - error
        - component: true
          html: true

    # Require PascalCase for user-defined JSX components
    react/jsx-pascal-case:
        - error

    # Disallow unnecessary curly braces in JSX
    react/jsx-curly-brace-presence:
        - error
        - never

    # eslint-plugin-react-hooks rules

    # Enforce rules of hooks
    react-hooks/rules-of-hooks: error

    # eslint-plugin-jest rules

    # Prefer "it" over "test"
    jest/consistent-test-it:
        - error
        - fn: it
          withinDescribe: it

    # Do not allow skipping tests
    jest/no-disabled-tests: error

    # eslint-plugin-jest-formatting rules

    # Require blank line before certain statements (ESLint rules don't work with Jest)
    jest-formatting/padding-around-all: error

    # @typescript-eslint rules

    # Require explicit return type on functions and class methods
    "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true

overrides:
    # Explicit assertions not required in most Cypress tests
    - files:
          - src/test/e2e/user-flows/*.test.js
      rules:
          jest/expect-expect:
              - off

settings:
    react:
        version: detect
