#
# Copyright 2022 StarTree Inc
#
# Licensed under the StarTree Community License (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.startree.ai/legal/startree-community-license
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT * WARRANTIES OF ANY KIND,
# either express or implied.
# See the License for the specific language governing permissions and limitations under
# the License.
#

---
extends:
    - stylelint-config-recommended
    - stylelint-config-recommended-scss
    - prettier
    - stylelint-config-prettier

rules:
    # Disallow double slash comments
    no-invalid-double-slash-comments: true

    # Require whitespace padding in comments
    comment-whitespace-inside: always

    # Require an empty line before rules except first nested rule or rules that follow comments
    rule-empty-line-before:
        - always
        - ignore:
              - first-nested
              - after-comment

    # Require lowercase property/values
    property-case: lower
    value-keyword-case: lower
    function-name-case: lower
    selector-pseudo-class-case: lower
    selector-pseudo-element-case: lower
    selector-type-case: lower
    media-feature-name-case: lower
    at-rule-name-case: lower
    unit-case: lower
    color-hex-case: lower

    # Require long notation for hex colors
    color-hex-length: long

    # Require a leading zero for fractional numbers less than 1
    number-leading-zero: always

    # Disallow trailing zeros in numbers
    number-no-trailing-zeros: true

    # Require generic family in list of font family names
    font-family-no-missing-generic-family-keyword: true

    # Require quotes around font family names where needed
    font-family-name-quotes: always-where-required
