resource_types:
- name: slack
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: src
  type: git
  icon: github
  source:
    uri: ((git-uri))
    branch: ((git-branch))
    private_key: ((ssh-private-key))
    ignore_paths:
    - kubernetes/helm

- name: slack
  type: slack
  icon: slack
  source:
    url: ((slack-webhook-url))
jobs:
- name: release-thirdeye
  plan:
  - get: src
  - task: release-thirdeye
    file: src/.concourse/tasks/release-thirdeye/release-thirdeye.yml
  on_success:
    put: slack
    params:
      channel: ((slack-channel))
      text: |
        Thirdeye release creation successful.
        ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  on_failure:
    put: slack
    params:
      channel: ((slack-channel))
      text: |
        <!channel> Failed to create a release for Thirdeye.
        ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
