resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: slack
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: slack
    icon: slack
    type: slack
    source:
      url: ((slack-webhook-url))
    
  - name: ci-src
    icon: github
    type: git
    source:
      uri: ((git-uri))
      branch: ((git-branch))
      paths:
      - .concourse

  # PR Resource
  - name: ((resources.pull_request.name))
    icon: git
    type: pull-request
    source:
      repository: startreedata/thirdeye
      access_token: ((github-token))
      paths: ((resources.pull_request.paths))

  # Merge Resource
  - name: ((resources.merge.name))
    icon: github
    type: git
    source:
      uri: ((git-uri))
      branch: ((git-branch))
      private_key: ((ssh-private-key))
      paths: ((resources.merge.paths))

jobs:
  # PR Task
  - name: ((project.id))-pr
    plan: ((pull_request.plan))
    on_success:
      do:
        - put: notify-success
          resource: ((resources.pull_request.name))
          params:
            base_context: startree-ci
            context: ((project.id))
            description: Pull Request for ((project.name)) has been successfully built.
            path: ((resources.pull_request.name))
            status: success
        - put: slack
          params:
            channel: ((slack-channel))
            text: |
              Pull Request for ((project.name)) has been successfully built.
              ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      do:
        - put: notify-failure
          resource: ((resources.pull_request.name))
          params:
            base_context: startree-ci
            context: ((project.id))
            description: Failed to build Pull Request for ((project.name))
            path: ((resources.pull_request.name))
            status: failure
        - put: slack
          params:
            channel: ((slack-channel))
            text: |
              <!channel> Failed to build Pull Request for ((project.name))
              ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  # Merge Tasks
  - name: ((project.id))-merge
    plan: ((merge.plan))
    on_success:
      do:
        - put: slack
          params:
            channel: ((slack-channel))
            text: |
              After merge to ((git-branch)), ((project.name)) has been successfully built
              ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    on_failure:
      do:
        - put: slack
          params:
            channel: ((slack-channel))
            text: |
              <!channel> Failed to build ((project.name)) after latest merge to ((git-branch))
              ((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
