import { TypographyOptions } from "@material-ui/core/styles/createTypography";

// CortexData Material-UI theme typography
export const typographyOptions = <TypographyOptions>{
    body1: {
        fontFamily: "Nunito",
        fontSize: "16px",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: "0.5px",
        lineHeight: "28px",
    },
    body2: {
        fontFamily: "Nunito",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: "0.25px",
        lineHeight: "20px",
    },
    button: {
        fontFamily: "Nunito",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: "0.75px",
        lineHeight: "16px",
        textTransform: "uppercase",
    },
    caption: {
        fontFamily: "Nunito",
        fontSize: "12px",
        fontStyle: "normal",
        fontWeight: "normal",
        letterSpacing: "0.4px",
        lineHeight: "16px",
    },
    fontFamily: "Quattrocento Sans, Nunito",
    h1: {
        fontFamily: "Quattrocento Sans",
        fontSize: "48px",
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: "-1.5px",
        lineHeight: "53px",
    },
    h2: {
        fontFamily: "Quattrocento Sans",
        fontSize: "40px",
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: "-0.5px",
        lineHeight: "44px",
    },
    h3: {
        fontFamily: "Quattrocento Sans",
        fontSize: "36px",
        fontStyle: "normal",
        fontWeight: "bold",
        lineHeight: "40px",
    },
    h4: {
        fontFamily: "Quattrocento Sans",
        fontSize: "32px",
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: "-0.25px",
        lineHeight: "35px",
    },
    h5: {
        fontFamily: "Quattrocento Sans",
        fontSize: "24px",
        fontStyle: "normal",
        fontWeight: "bold",
        lineHeight: "27px",
    },
    h6: {
        fontFamily: "Quattrocento Sans",
        fontSize: "20px",
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: "0.15px",
        lineHeight: "22px",
    },
    overline: {
        fontFamily: "Nunito",
        fontSize: "10px",
        fontStyle: "normal",
        fontWeight: 300,
        letterSpacing: "1.5px",
        lineHeight: "16px",
        textTransform: "uppercase",
    },
    subtitle1: {
        fontFamily: "Nunito",
        fontSize: "16px",
        fontStyle: "normal",
        fontWeight: "bold",
        letterSpacing: "0.15px",
        lineHeight: "24px",
    },
    subtitle2: {
        fontFamily: "Nunito",
        fontSize: "14px",
        fontStyle: "normal",
        fontWeight: "bold",
        lineHeight: "20px",
    },
};
