// CortexData Material-UI theme dimensions
export const Dimension = {
    WIDTH_BORDER_DEFAULT: 1,
    WIDTH_BORDER_BUTTON_OUTLINED: 2,
    WIDTH_SNACKBAR_DEFAULT: 400,
    WIDTH_PAGE_CONTENTS_DEFAULT: 960,
    RADIUS_BORDER_DEFAULT: 8,
    SPACING_GRID_DEFAULT: 2,
    // Visualizations
    WIDTH_VISUALIZATION_STROKE_DEFAULT: 1.5,
    WIDTH_VISUALIZATION_STROKE_DASHARRAY: 2.5,
} as const;
