{{- if .Values.config.holidayLoaderKey }}
apiVersion: v1
kind: Secret
metadata:
  name: holiday-loader-key
type: Opaque
data:
  holiday-loader-key.json: {{ .Values.config.holidayLoaderKey | b64enc }}
{{- end }}
