// Material-UI theme dimensions
export const Dimension = {
    WIDTH_BORDER_DEFAULT: 1,
    WIDTH_BORDER_BUTTON_OUTLINED: 2,
    WIDTH_SNACKBAR_DEFAULT: 400,
    WIDTH_PAGE_CONTENTS_DEFAULT: 960,
    HEIGHT_INPUT_DEFAULT: 56,
    RADIUS_BORDER_DEFAULT: 8,
    SPACING_GRID_DEFAULT: 2,
    // Visualizations
    WIDTH_VISUALIZATION_STROKE_DEFAULT: 1,
    WIDTH_VISUALIZATION_STROKE_CURRENT: 1,
    WIDTH_VISUALIZATION_STROKE_BASELINE: 4,
    RADIUS_VISUALIZATION_HOVER_MARKER: 3,
    WIDTH_VISUALIZATION_STROKE_HOVER_MARKER: 2,
    DASHARRAY_VISUALIZATION_HOVER_MARKER: 3,
    HEIGHT_VISUALIZATION_LEGEND_GLYPH: 15,
    WIDTH_VISUALIZATION_LEGEND_GLYPH: 15,
} as const;
