// Material-UI theme dimensions
export const Dimension = {
    WIDTH_BORDER_DEFAULT: 1,
    WIDTH_BORDER_BUTTON_OUTLINED: 2,
    WIDTH_SNACKBAR_DEFAULT: 420,
    WIDTH_DRAWER_DEFAULT: 290,
    WIDTH_DRAWER_MINIMIZED: 50,
    WIDTH_PAGE_CONTENTS_CENTERED: 960,
    MIN_WIDTH_MENU: 250,
    HEIGHT_INPUT_DEFAULT: 56,
    HEIGHT_INPUT_SMALL_DEFAULT: 37,
    RADIUS_BORDER_DEFAULT: 8,
    SPACING_GRID_DEFAULT: 2,
    // Visualizations
    WIDTH_VISUALIZATION_STROKE_DEFAULT: 1,
    WIDTH_VISUALIZATION_STROKE_CURRENT: 1.5,
    WIDTH_VISUALIZATION_STROKE_BASELINE: 3,
    DASHARRAY_VISUALIZATION_BASELINE: 2,
    WIDTH_VISUALIZATION_STROKE_HOVER_MARKER: 1,
    DASHARRAY_VISUALIZATION_HOVER_MARKER: 2,
    RADIUS_VISUALIZATION_HOVER_MARKER: 5,
    HEIGHT_VISUALIZATION_LEGEND_GLYPH: 15,
    WIDTH_VISUALIZATION_LEGEND_GLYPH: 15,
} as const;
