---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 14.7.0

params:
  ARTIFACTORY_EMAIL: ((artifactory-email))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
  ARTIFACTORY_USERNAME: ((artifactory-username))

inputs:
  - name: ci-src

outputs:
  - name: project-dependencies
    path: ci-src/thirdeye-ui/node_modules

run:
  dir: ci-src
  path: .concourse/tasks/thirdeye-ui/prepare-thirdeye-ui.sh
