merge:
  plan:
    - get: ci-src
    - get: thirdeye-ui-merge-src
      trigger: true
    - task: prepare-thirdeye-ui
      file: thirdeye-ui-merge-src/.concourse/tasks/thirdeye-ui/prepare-thirdeye-ui.yml
      input_mapping:
        ci-src: thirdeye-ui-merge-src
    - in_parallel:
        fail_fast: true
        steps:
          - task: build-thirdeye-ui
            file: thirdeye-ui-merge-src/.concourse/tasks/thirdeye-ui/build-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-merge-src
          - task: lint-thirdeye-ui
            file: thirdeye-ui-merge-src/.concourse/tasks/thirdeye-ui/lint-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-merge-src
          - task: test-thirdeye-ui
            file: thirdeye-ui-merge-src/.concourse/tasks/thirdeye-ui/test-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-merge-src
    - task: publish-thirdeye-ui
      file: thirdeye-ui-merge-src/.concourse/tasks/thirdeye-ui/publish-thirdeye-ui.yml
      input_mapping:
        ci-src: thirdeye-ui-merge-src
pull_request:
  plan:
    - get: thirdeye-ui-pr-src
      trigger: true
      version: every
    - put: notify-pending
      resource: thirdeye-ui-pr-src
      params:
        base_context: startree-ci
        context: thirdeye-ui
        description: "Pull Request triggered a ThirdEye UI build"
        path: thirdeye-ui-pr-src
        status: pending
    - task: prepare-thirdeye-ui
      file: thirdeye-ui-pr-src/.concourse/tasks/thirdeye-ui/prepare-thirdeye-ui.yml
      input_mapping:
        ci-src: thirdeye-ui-pr-src
    - in_parallel:
        fail_fast: true
        steps:
          - task: build-thirdeye-ui
            file: thirdeye-ui-pr-src/.concourse/tasks/thirdeye-ui/build-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-pr-src
          - task: lint-thirdeye-ui
            file: thirdeye-ui-pr-src/.concourse/tasks/thirdeye-ui/lint-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-pr-src
          - task: test-thirdeye-ui
            file: thirdeye-ui-pr-src/.concourse/tasks/thirdeye-ui/test-thirdeye-ui.yml
            input_mapping:
              ci-src: thirdeye-ui-pr-src
project:
  id: thirdeye-ui
  name: ThirdEye UI
  path: thirdeye-ui
resources:
  # PR Resource
  pull_request:
    name: thirdeye-ui-pr-src
    paths:
      - .concourse
      - thirdeye-ui
  # Merge Resource
  merge:
    name: thirdeye-ui-merge-src
    paths:
      - thirdeye-ui
