
{{ if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirdeye.scheduler.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.scheduler.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "thirdeye.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.scheduler.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thirdeye.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.scheduler.name }}
      annotations:
        prometheus.io/port: {{ .Values.scheduler.port | quote }}
        prometheus.io/path: "/admin/prometheus"
{{ toYaml .Values.scheduler.podAnnotations | indent 8 }}
    spec:
      {{- if .Values.image.pullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretsName | quote}}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.scheduler.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.scheduler.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.scheduler.tolerations | indent 8 }}
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
            "server"
        ]
        ports:
          - containerPort: {{ .Values.scheduler.port }}
            protocol: TCP
        volumeMounts:
          - name: thirdeye-config
            mountPath: "/home/thirdeye/thirdeye/config/server.yaml"
            subPath: "server.yaml"
            readOnly: true
          {{- if .Values.config.holidayLoaderKey }}
          - name: thirdeye-config
            mountPath: "/home/thirdeye/thirdeye/config/holiday-loader-key.json"
            subPath: "holiday-loader-key.json"
            readOnly: true
        {{- end }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
      restartPolicy: Always
      volumes:
        - name: thirdeye-config
          configMap:
            name: thirdeye-scheduler
{{ end }}
