
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirdeye.ui.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.ui.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ include "thirdeye.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.ui.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "thirdeye.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.ui.name }}
      annotations:
{{ toYaml .Values.ui.podAnnotations | indent 8 }}
    spec:
      {{- if .Values.ui.image.pullSecretsName }}
      imagePullSecrets:
        - name: "{{ .Values.ui.image.pullSecretsName }}"
      {{- end }}
      nodeSelector:
{{ toYaml .Values.ui.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.ui.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.ui.tolerations | indent 8 }}
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        args: []
        ports:
          - containerPort: {{ .Values.ui.port }}
            protocol: TCP
        env:
          - name: NGINX_PORT
            value: "{{ .Values.ui.port }}"
          - name: THIRDEYE_API_BASE_URL
            value: "http://{{ template "thirdeye.coordinator.headless" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.coordinator.port }}"
          - name: NGINX_ENVSUBST_TEMPLATE_DIR
            value: /home/thirdeye/nginx/templates
          - name: NGINX_ENVSUBST_OUTPUT_DIR
            value: /home/thirdeye/nginx/conf.d

      restartPolicy: Always
