
{{ if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "thirdeye.worker.headless" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.worker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    # [pod_name].[service_name].[namespace].svc.cluster.local
    - port: {{ .Values.worker.port }}
  selector:
    app: {{ include "thirdeye.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.worker.name }}
{{ end }}
