# Default values for ThirdEye Deployment

image:
  repository: repo.startreedata.io/external-docker-registry/thirdeye
  tag: latest
  pullPolicy: Always
  pullSecretsName: startree

ui:
  image:
    repository: repo.startreedata.io/external-docker-registry/thirdeye-ui
    tag: latest
    pullPolicy: Always
    pullSecretsName: startree
  enabled: true
  name: ui
  port: 8081
  publicUrl: http://localhost:8081
  serviceType: LoadBalancer

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

coordinator:
  enabled: true
  name: coordinator
  replicaCount: 1
  port: 8080
  serviceType: LoadBalancer

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations:
    prometheus.io/scrape: "false"
  # Expose prometheus metrics. Should be true if prometheus.io/scrape (above) is true.
  prometheus:
    enabled: false

scheduler:
  enabled: true
  name: scheduler
  port: 8082
  serviceType: ClusterIP

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations:
    prometheus.io/scrape: "false"
  # Expose prometheus metrics. Should be true if prometheus.io/scrape (above) is true.
  prometheus:
    enabled: false

worker:
  enabled: true
  name: worker
  port: 8083
  serviceType: ClusterIP

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations:
    prometheus.io/scrape: "false"
  # Expose prometheus metrics. Should be true if prometheus.io/scrape (above) is true.
  prometheus:
    enabled: false

# Persistence layer configuration
mysql:
  mysqlRootPassword: password
  mysqlUser: uthirdeye
  mysqlPassword: pass
  mysqlDatabase: thirdeye

  # Note:  initializationFiles parameter needs to be injected via command line to
  # complete the DB setup.

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 4G
  storageClass: ""

smtp:
  host: localhost
  port: 65
  username: tobefedexternally
  password: tobefedexternally
  secretKeyRef:
    name: smtp-credentials

# Do not remove me.
config:
  description: placeholder for common configs accross coordinator and worker

# Optional: Enable for ingress
traefik:
  coordinator:
    enabled: false
  enabled: true
