---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: daniellavoie/startree-platform-ci
    tag: latest

inputs:
  - name: ci-src
  - name: build
  - name: chart-version

params:
  CHART_PATH: .
  CHART_PREFIX: thirdeye
  HELM_REPOSITORY_URL: ((helm-push-uri))
  HELM_REPOSITORY_TOKEN: ((artifactory-password))

run:
  path: ci-src/.concourse/tasks/publish-helm-chart/publish-helm-chart.sh
