
# curl -X POST "http://localhost:8080/api/alerts/evaluate" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"alert\": { \"name\": \"pc5\", \"description\": \"Percentage drop\", \"nodes\": { \"detection_rule_1\": { \"type\": \"DETECTION\", \"subType\": \"PERCENTAGE_RULE\", \"metric\": { \"name\": \"views\", \"dataset\": { \"name\": \"pageviews\" } }, \"params\": { \"offset\": \"wo1w\", \"percentageChange\": 0.1, \"pattern\": \"down\" } } } }, \"start\": 1577865600000, \"end\": 1590994800000}"
POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "PercentageChange1",
    "description": "Percentage drop",
    "nodes": {
      "detection_rule_1": {
        "type": "DETECTION",
        "subType": "PERCENTAGE_RULE",
        "metric": {
          "name": "views",
          "dataset": {
            "name": "pageviews"
          }
        },
        "params": {
          "offset": "wo1w",
          "percentageChange": 0.1,
          "pattern": "down"
        }
      }
    }
  },
  "start": 1577865600000,
  "end": 1590994800000
}

<> 2021-06-28T154714.200.json
<> 2021-06-28T121437.200.json
<> 2021-06-28T120839.200.json

###

POST http://localhost:8080/api/alerts/evaluate
accept: application/json
Content-Type: application/json

{
  "alert": {
    "name": "AbsoluteChange1",
    "description": "Absolute Change",
    "nodes": {
      "detection_rule_1": {
        "type": "DETECTION",
        "subType": "ABSOLUTE_CHANGE_RULE",
        "metric": {
          "name": "views",
          "dataset": {
            "name": "pageviews"
          }
        },
        "params": {
          "offset": "wo1w",
          "absoluteChange": 100000
        }
      }
    }
  },
  "start": 1577865600000,
  "end": 1590994800000
}

<> 2021-06-29T123648.200.json
<> 2021-06-29T123414.200.json


###
