# curl -X POST "http://localhost:8080/api/data-sources" -H "accept: application/json" -H "Content-Type: application/json" -d "[ { \"name\": \"pinot1\", \"type\": \"pinot\", \"properties\": { \"zookeeperUrl\": \"pinot-zookeeper:2181\", \"clusterName\": \"pinot-quickstart\", \"controllerConnectionScheme\": \"http\", \"controllerHost\": \"pinot-controller\", \"controllerPort\": 9000, \"cacheLoaderClassName\": \"org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader\" }, \"metaList\": [ { \"classRef\": \"org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource\" } ] }]"
POST http://localhost:8080/api/data-sources
accept: application/json
Content-Type: application/json

[
  {
    "name": "pinotQuickStartLocal",
    "type": "pinot",
    "properties": {
      "zookeeperUrl": "localhost:2123",
      "clusterName": "QuickStartCluster",
      "controllerConnectionScheme": "http",
      "controllerHost": "localhost",
      "controllerPort": 9000
    }
  }
]

###

# curl -X POST "http://localhost:8080/api/data-sources/onboard-all" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "dataSourceName=pinot1"
POST http://localhost:8080/api/data-sources/onboard-all
accept: application/json
Content-Type: application/x-www-form-urlencoded

name=pinotQuickStartLocal

###

