name: TE UI - E2E Tests
on:
  push:
    branches:
      - e2e-setup
    paths:
      - thirdeye-ui/**
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            thirdeye-ui

      - name: Install node and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: './thirdeye-ui/package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npm exec playwright install --with-deps

      - name: Run local server
        run: VERCEL_ACCESS_TOKEN=${{ secrets.E2E_TOKEN }} TE_DEV_PROXY_SERVER={{ secrets.E2E_PROXY}} npm run start

      - name: Run Playwright tests
        run: npm exec playwright test