name: TE UI - E2E Tests
on:
  push:
    branches:
      - harshil/e2e-tests
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            thirdeye-ui

      - name: Install node and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
          cache-dependency-path: "./thirdeye-ui/package-lock.json"

      - name: Install dependencies
        run: |
          cd thirdeye-ui
          npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: |
          cd thirdeye-ui
          npx playwright install --with-deps

      - name: Run local server
        run: |
          cd thirdeye-ui
          npm run start &
        env:
          VERCEL_ACCESS_TOKEN: ${{ secrets.E2E_TOKEN }}
          TE_DEV_PROXY_SERVER: ${{ secrets.E2E_PROXY }}

      - name: Wait for server to be ready
        run: |
          until curl -s http://localhost:7004; do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Run Playwright tests
        run: |
          cd thirdeye-ui
          npx playwright test
      - name: Stop local server
        run: |
          kill $(lsof -t -i:7004)
